using kl_eCom.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Net.Mail;
using System.Net;
using System.Threading;

namespace kl_eCom.Web.Controllers
{
    [Authorize(Roles = "Customer, Vendor")]
    public class CustomerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetStates(string idStr = "")
        {
            if (string.IsNullOrEmpty(idStr)) return null;
            int id = int.Parse(idStr);

            if (id == 0) return null;

            IEnumerable<SelectListItem> states = db.States
                .Where(m => m.CountryId == id)
                .OrderBy(m => m.Name)
                .Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.Name
                }).ToList();

            return Json(states, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetCities(string idStr = "")
        {
            if (string.IsNullOrEmpty(idStr)) return null;
            int id = int.Parse(idStr);

            if (id == 0) return null;

            IEnumerable<SelectListItem> cities = db.Places
                .Where(m => m.StateId == id)
                .OrderBy(m => m.Name)
                .Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();

            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MyOrders()
        {
            var usrId = User.Identity.GetUserId();

            return View(db.Orders
                .Include(m => m.OrderItems)
                .Include(m => m.Customer)
                .Where(m => m.Customer.ApplicationUserId == usrId)
                .OrderByDescending(m => m.OrderDate)
                .ToList());
        }

        public ActionResult Cancellation(int? id)
        {
            if (id == null) return View("Error");

            return View(new CustomerCancellationViewModel {
                Id = (int)id,
                Order = db.Orders
                    .Include(m => m.OrderItems)
                    .FirstOrDefault(m => m.Id == id)
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cancellation(CustomerCancellationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var order = db.Orders
                    .Include(m => m.Customer)
                    .Include(m => m.Customer.User)
                    .FirstOrDefault(m => m.Id == model.Id);

                string itemsStr = Request.Form["CanceledItems"];

                if (itemsStr is null) itemsStr = "";
                var cnclsList = itemsStr.Split(',').Select(sValue => sValue.Trim()).ToArray() as string[];
                if (cnclsList is null) cnclsList = new string[] { };

                string subject = "#" + order.OrderNumber + ": Cancellation Request";
                string message = "Cancellation request has been generated by " + order.Customer.User.FirstName
                        + " " + order.Customer.User.LastName + ", for the following items:\n\n";

                for (int i = 0; i < cnclsList.Count(); i++)
                {
                    if (cnclsList[i] == "") continue;
                    int id = int.Parse(cnclsList[i]);
                    var orderItm = db.OrderItems
                        .Include(m => m.Vendor)
                        .FirstOrDefault(m => m.Id == id);
                    orderItm.Status = Utilities.OrderStatus.CancellationRequested;

                    int refId = db.Refferals
                            .Include(m => m.Customer)
                            .Include(m => m.Vendor)
                            .FirstOrDefault(m => m.Customer.Id == order.EcomUserId
                                && m.Vendor.Id == orderItm.EcomUserId).Id;
                    db.OrderInformation.Add(new Utilities.OrderStateInfo
                    {
                        Type = Utilities.ChangeType.Cancellation,
                        InitialDate = DateTime.Now,
                        RefferalId = refId,
                        OrderItemId = orderItm.Id,
                    });

                    db.Entry(orderItm).State = EntityState.Modified;

                    string tempMessage = "";
                    tempMessage += "\tProduct: " + orderItm.ProductName + ", Quantity: " + orderItm.Qty + 
                        ", Value = Rs. " + orderItm.FinalCost + " (" + orderItm.Price + " x " + orderItm.Qty + ")\n";


                    tempMessage += "\nContact customer at: " + order.Customer.User.PhoneNumber + "\n\n";
                    tempMessage += "Regards,\nKhuslife E-com Team";

                    FireEmail(orderItm.Vendor.User.Email, subject, message + tempMessage);
                }
                

                db.SaveChanges();

                return RedirectToAction("MyOrders");
            }
            return View("Error");
        }

        private void FireEmail(string to, string subject, string message, bool isBodyHtml = false)
        {
            var klEmail = "khushlifeecommerce@gmail.com";
            var klPass = "klEcom1234";
            using (MailMessage mm = new MailMessage(klEmail, to))
            {
                mm.Subject = subject;
                mm.Body = message;
                mm.IsBodyHtml = isBodyHtml;
                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(klEmail, klPass);
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                }
            }
        }

        private string generateStringOTP(int len)
        {
            // All possible characters of my OTP 
            string str = "abcdefghijklmnopqrstuvwxyzABCD"
               + "EFGHIJKLMNOPQRSTUVWXYZ";
            int n = str.Length;

            // String to hold my OTP 
            string OTP = "";

            for (int i = 1; i <= len; i++)
            {
                OTP += (str[(new Random()).Next(n)]);
                Thread.Sleep(100);
            }

            return (OTP);
        }

        private string generateNumericalOTP(int len)
        {
            // All possible characters of my OTP 
            string str = "0123456789";
            int n = str.Length;

            // String to hold my OTP 
            string OTP = "";

            for (int i = 1; i <= len; i++)
                OTP += (str[(new Random()).Next(n)]);

            return (OTP);
        }

        public ActionResult VerifyEmail()
        {
            var userId = User.Identity.GetUserId();

            var ecomUser = db.EcomUsers
                             .Include(m => m.User)
                             .Include(m => m.VendorDetails)
                             .Where(m => m.ApplicationUserId == userId)
                             .FirstOrDefault();

            if (ecomUser.User.EmailConfirmed)
                return View("Error");

            ecomUser.User.EmailCode = generateStringOTP(6);

            FireEmail(ecomUser.User.Email,
                "Email Verification Mail", "Please click the link below in order to verify your email,\n\n"
                + /*"http://khushlifeecom.azurewebsites.net"*/ "http://localhost:50208"
                + Url.Action("VerifyEmailConfirm",
                new { userId = ecomUser.ApplicationUserId, secret = ecomUser.User.EmailCode }));

            db.Entry(ecomUser).State = EntityState.Modified;
            db.SaveChanges();

            return View();
        }

        public ActionResult VerifyEmailConfirm(string userId, string secret)
        {
            if (string.IsNullOrEmpty(userId) || userId != User.Identity.GetUserId())
                return View("Error");

            var ecomUser = db.EcomUsers
                             .Include(m => m.User)
                             .Where(m => m.ApplicationUserId == userId)
                             .FirstOrDefault();

            if (ecomUser is null) return View("Error");


            if (string.IsNullOrEmpty(secret) || secret != ecomUser.User.EmailCode)
                return View("Error");

            ecomUser.User.EmailConfirmed = true;
            db.Entry(ecomUser).State = EntityState.Modified;

            db.SaveChanges();

            return View();
        }

        public ActionResult VerifyMobile()
        {


            return View();
        }

        public ActionResult CustomerProfile()
        {
            string userId = User.Identity.GetUserId();

            var ecomUser = db.EcomUsers
                .Include(m => m.User)
                .FirstOrDefault(m => 
                    m.ApplicationUserId == userId);

            if (ecomUser is null) return View("Error");

            var model = new CustomerProfileManageViewModel {
                FullName = ecomUser.User.FirstName + " " + ecomUser.User.LastName,
                Email = ecomUser.User.Email,
                MobileNumber = ecomUser.User.PhoneNumber,
                DOB = ecomUser.User.DOB,
                IsEmailVerified = ecomUser.User.EmailConfirmed,
                IsMobileVerified = ecomUser.User.PhoneNumberConfirmed
            };

            return View(model);
        }

        public ActionResult EditProfile()
        {
            var userId = User.Identity.GetUserId();

            var ecomUser = db.EcomUsers
                .Include(m => m.User)
                .FirstOrDefault(m => m.ApplicationUserId == userId);

            if (ecomUser is null)
                return View("Error");

            var model = new CustomerEditProfileViewModel {
                FirstName = ecomUser.User.FirstName,
                LastName = ecomUser.User.LastName,
                DOB = ecomUser.User.DOB
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile(CustomerEditProfileViewModel model)
        {
            if (ModelState.IsValid)
            {


                return RedirectToAction("CustomerProfile");
            }

            return View("Error");
        }

        public ActionResult Addresses()
        {
            var usrId = User.Identity.GetUserId();

            return View(new CustomerAddressesIndexViewModel {
                Addresses = db.Addresses
                    .Where(m => m.ApplicationUserId == usrId)
                    .Include(m => m.State)
                    .Include(m => m.Place)
                    .Include(m => m.Country)
                    .ToList()
            });
        }

        public ActionResult CreateAddress(string returnUrl = "")
        {
            if (returnUrl != "" && Url.IsLocalUrl(returnUrl))
            {
                TempData["ReturnUrl"] = returnUrl;
            }

            var model = new CustomerCreateAddressViewModel();

            model.Countries = db.Countries
                .OrderBy(m => m.Name)
                .Select(m => new SelectListItem
                {
                    Value = m.Id.ToString(),
                    Text = m.Name
                }).ToList();

            model.States = new List<SelectListItem> {
                new SelectListItem {
                    Value = null,
                    Text = ""
                }
            };

            model.Cities = new List<SelectListItem>
            {
                new SelectListItem {
                    Value = null,
                    Text = ""
                }
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAddress(CustomerCreateAddressViewModel model)
        {
            var usrId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Addresses.Add(new Utilities.Address {
                    ApplicationUserId = usrId,
                    Name = model.Name,
                    Line1 = model.Line1,
                    Line2 = model.Line2,
                    Line3 = model.Line3,
                    Landmark = model.Landmark,
                    PlaceId = model.SelectedCity,
                    Zip = model.Zip,
                    StateId = model.SelectedState,
                    CountryId = model.SelectedCountry
                });
                db.SaveChanges();

                if (TempData["ReturnUrl"] is string returnUrl)
                        return Redirect(returnUrl);

                return RedirectToAction("Addresses");
            }
            return View(model);
        }

        public ActionResult EditAddress(int? id, string returnUrl = "")
        {
            if (returnUrl != "" && Url.IsLocalUrl(returnUrl))
            {
                TempData["ReturnUrl"] = returnUrl;
            }
            if (id == null) return View("Error");
            var usrId = User.Identity.GetUserId();
            var addr = db.Addresses
                        .FirstOrDefault(m => m.Id == id 
                        && m.ApplicationUserId == usrId);
            if (addr == null) return View("Error");

            var countries = db.Countries
                .OrderBy(m => m.Name)
                .Select(m => new SelectListItem
                {
                    Value = m.Id.ToString(),
                    Text = m.Name
                }).ToList();

            var states = db.States
                .OrderBy(m => m.Name)
                .Select(m => new SelectListItem
                {
                    Value = m.Id.ToString(),
                    Text = m.Name
                }).ToList();

            var cities = db.Places
                .OrderBy(m => m.Name)
                .Select(m => new SelectListItem
                {
                    Value = m.Id.ToString(),
                    Text = m.Name
                }).ToList();

            return View(new CustomerEditAddressViewModel {
                Id = (int)id,
                Name = addr.Name,
                Line1 = addr.Line1,
                Line2 = addr.Line2,
                Line3 = addr.Line3,
                SelectedCity = addr.PlaceId,
                SelectedState = addr.StateId,
                Landmark = addr.Landmark,
                Zip = addr.Zip,
                SelectedCountry = addr.CountryId,
                Countries = countries,
                States = states,
                Cities = cities
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAddress(CustomerEditAddressViewModel model)
        {
            if (ModelState.IsValid)
            {
                var addr = db.Addresses.FirstOrDefault(m => m.Id == model.Id);
                if (addr != null)
                {
                    addr.Name = model.Name;
                    addr.Line1 = model.Line1;
                    addr.Line2 = model.Line2;
                    addr.Line3 = model.Line3;
                    addr.Landmark = model.Landmark;
                    addr.StateId = model.SelectedState;
                    addr.Zip = model.Zip;
                    addr.PlaceId = model.SelectedCity;
                    addr.CountryId = model.SelectedCountry;
                    db.Entry(addr).State = EntityState.Modified;
                    db.SaveChanges();

                    if (TempData["ReturnUrl"] is string returnUrl)
                        return Redirect(returnUrl);

                    return RedirectToAction("Addresses");
                }
                else
                {
                    return View("Error");
                }
            }
            return View(model);
        }

        public ActionResult DeleteAddress(int? id, string returnUrl = "")
        {
            if (returnUrl != "" && Url.IsLocalUrl(returnUrl))
            {
                TempData["ReturnUrl"] = returnUrl;
            }
            if (id == null) return View("Error");
            var usrId = User.Identity.GetUserId();
            var addr = db.Addresses
                        .Include(m => m.Place)
                        .Include(m => m.State)
                        .Include(m => m.Country)
                        .FirstOrDefault(m => m.Id == id
                          && m.ApplicationUserId == usrId);
            if (addr == null) return View("Error");
            return View(new CustomerDeleteAddressViewModel
            {
                Id = (int)id,
                Name = addr.Name,
                Line1 = addr.Line1,
                Line2 = addr.Line2,
                Line3 = addr.Line3,
                Landmark = addr.Landmark,
                State = addr.State.Name,
                City = addr.Place.Name,
                Zip = addr.Zip,
                Country = addr.Country.Name
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAddress(CustomerDeleteAddressViewModel model)
        {
            if (model.Id != 0)
            {
                var addr = db.Addresses.FirstOrDefault(m => m.Id == model.Id);
                if (addr != null)
                {
                    db.Entry(addr).State = EntityState.Deleted;
                    db.SaveChanges();

                    if (TempData["ReturnUrl"] is string returnUrl)
                        return Redirect(returnUrl);

                    return RedirectToAction("Addresses");
                }
                else
                {
                    return View("Error");
                }
            }
            return View(model);
        }
    }
}