// <auto-generated />
namespace kl_eCom.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_VendorRegistration_Details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_VendorRegistration_Details));
        
        string IMigrationMetadata.Id
        {
            get { return "201806250814020_Added_VendorRegistration_Details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
