// <auto-generated />
namespace kl_eCom.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Discounts_Edited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Discounts_Edited));
        
        string IMigrationMetadata.Id
        {
            get { return "201807270748402_Discounts_Edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
